name: CI

on:
  push:
    branches:
      - main
      - 'refs/tags/*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Log in to the container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker image
        run: docker build -t ghcr.io/${{ github.repository }}/my-app:${{ github.sha }} .

      - name: Push Docker image
        run: docker push ghcr.io/${{ github.repository }}/my-app:${{ github.sha }}

  test:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Log in to the container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Pull Docker image
        run: docker pull ghcr.io/${{ github.repository }}/my-app:${{ github.sha }}

      - name: Run tests
        run: |
          docker run ghcr.io/${{ github.repository }}/my-app:${{ github.sha }} python -m unittest discover -s tests

